### ISSUE TITLE
Basic car connectivity over a network

### ISSUE THREAD

**Issue by a-brannen** [DIT112-V21/group-01#19]
**User Story**
As a user, I want the car to be able to receive and act upon remote commands via network.

**Requirements**
The car must be able to establish and maintain a connection to an MQTT broker, including publishing and receiving messages.

**System Level Tasks:**
_Basic connectivity_
- [x] The car can connect to an MQTT broker.
- [x] The car can receive messages from an MQTT broker.
- [x] The car can print messages in the console.
- [x] The car can publish messages to the MQTT broker.

_Controls_
- [x] The car's speed can be set via MQTT.
- [x] The car's steering angle can be set via MQTT.

_Handling Exceptions_

- [x] The car's backend sanitizes received instructions before evaluating them.
- [x] The car handles invalid instructions without crashing.
- [x] The car gracefully handles the loss of connection to the broker, i.e. the car stops and waits.
- [x] The car tries to automatically reconnect to the broker if connection is lost.

**Notes**: 

- MQTT Client: https://github.com/256dpi/arduino-mqtt
- Arduino MQTT ex.: https://github.com/DIT112-V21/smartcar-mqtt-controller/blob/main/arduino/smartcar_mqtt/smartcar_mqtt.ino

**Comment by dekmm** [comment]
It seems there's nothing we can do about empty payloads from the Arduino side. Whenever the Arduino MQTT client receives an empty payload, even without any further processing of the payload, the sketch crashes.
