### ISSUE TITLE
Fix MQTT message pollution in joystick 

### ISSUE THREAD

**Issue by gsastraw** [DIT112-V21/group-01#22]
There is an issue with the joystick where the inputs given do not always register all the messages. The joystick is essentially a map with an X and Y axis that calculates the position of the knob at every given point in time, and therefore a lot of messages are published to the MQTT broker in a short period of time. 

Therefore, the joystick is as of now somewhat inaccurate. 

A suggestion given previously was to not send messages on every change but after a certain period and to store the latest joystick input and have a cron job publish the value to an MQTT topic.

**Comment by nk-io** [comment]
Teams decided that this problem is solved with the previous updates and does not occur on the projects anymore.
