### ISSUE TITLE
User Interface Mockup

### ISSUE THREAD

**Issue by ktpa** [DIT112-V21/group-01#26]
As a front-end developer, I want to be able to reference a mockup when I create the elements so that my workflow is enhanced without creative blocks.

Acceptance Criteria:
A complete mockup of two screens:
- Login
- Main

**Comment by gsastraw** [comment]
Initial draft (co-authored by @ktpa): 

![login_screen](https://user-images.githubusercontent.com/70916445/115704930-3a02f580-a36c-11eb-951f-7dea8e2fae46.png)
<img width="309" alt="Screenshot 2021-04-22 at 13 12 31" src="https://user-images.githubusercontent.com/70916445/115705161-80f0eb00-a36c-11eb-9fcb-4a449cedde33.png">
![drive_screen](https://user-images.githubusercontent.com/70916445/115704920-38d1c880-a36c-11eb-8d1b-91555354c698.png)
![tweak_AlSet](https://user-images.githubusercontent.com/70916445/115704938-3bccb900-a36c-11eb-991a-7cbb8cce2a2e.png)
