### ISSUE TITLE
UI implementation

### ISSUE THREAD

**Issue by a-brannen** [DIT112-V21/group-01#27]
**User Story**
As a front-end developer, I want to implement a graphical user interface according to the mockup, so that my colleagues can connect their functions and make the app incredible.

**Acceptance Criteria:**
A responsive user interface consistent with the mockup screens.

**Comment by a-brannen** [comment]
Issue ongoing (Sprint 2 -->) as UI is continuously developed in response to newly opened issues.

**Comment by gsastraw** [comment]
finished our super slick UI in time, ggwp my bruddas
