### ISSUE TITLE
Create separate topics for incoming/outgoing MQTT messages

### ISSUE THREAD

**Issue by dekmm** [DIT112-V21/group-01#38]
With the current way our MQTT topics are structured, the Arduino MQTT client can receive the same messages that it publishes. 

An example of this is the way we send out camera information to our MQTT broker. We're currently sending that info to a topic called `/smartcar/control/camera`, but since we're subscribed to all messages that come to `/smartcar/control/#`, the client receives those messages right back to itself.

A convenient way to get around this issue would be to create separate input/output topics, such as `/smartcar/control/input/#` and `smartcar/control/output/#`

**Comment by platisd** [comment]
Also consider `/smartcar/camera`

**Comment by dekmm** [comment]
`/smartcar/camera` was chosen via a group vote
![Discord_LvQeRBKaEp](https://user-images.githubusercontent.com/7628664/116206973-a94b6180-a73f-11eb-93e8-a118cadbc513.png)
