### ISSUE TITLE
Valet Mode 

### ISSUE THREAD

**Issue by nk-io** [DIT112-V21/group-01#7]
As a user of AlSet, I would like to be able to limit the top speed of the car so that I can ensure safety even when the driver is not experienced.

Acceptance Criteria:
Option to manually limit the top speed

**Comment by gsastraw** [comment]
moved to sprint#2

**Comment by a-brannen** [comment]
After discussion with the team, we have decided to discontinue development on this issue due to our current design choices (i.e. joystick and voice recognition).
